In [1]:
import numpy as np
arr=np.array([4,9,2,6,5])
print("array is",arr)

#a
arr_added=arr+2
print("array after adding 2",arr_added)

#b
arr_multiplied=arr*2
print("array after multiplying 2",arr_multiplied)

#c
arr_divided=arr/2
print("array after dividing 2",arr_divided)

array is [4 9 2 6 5]
array after adding 2 [ 6 11  4  8  7]
array after multiplying 2 [ 8 18  4 12 10]
array after dividing 2 [2.  4.5 1.  3.  2.5]


In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr_reversed=arr[::-1]
print(arr_reversed)

#b
#i
x=np.array([1,2,3,4,5,1,2,1,1,1])
most_frq=np.bincount(x).argmax()
print("most frequent value",most_frq)
indices=np.where(x==most_frq)[0]
print("indices of most frequent value",indices)
#ii
x=np.array([1,1,1,2,3,4,2,4,3,3])
most_frq_ii=np.bincount(x).argmax()
print("most frequent value",most_frq_ii)
indices_ii=np.where(x==most_frq_ii)[0]
print("indices of most frequent value",indices_ii)

[6 5 4 3 2 1]
most frequent value 1
indices of most frequent value [0 5 7 8 9]
most frequent value 1
indices of most frequent value [0 1 2]


In [2]:

import numpy as np
arr=np.array([[40,90,30],[30,80,60],[10,20,90]])
#a
print(arr[0][1])

#b
print(arr[2][0])

90
10


In [3]:
import numpy as np
nishtha=np.linspace(10,100,25)
print("original array :\n",nishtha)
print("dimensions:",nishtha.ndim)
print("shape:",nishtha.shape)
print("size:",nishtha.size)
print("data type :",nishtha.dtype)
print("bytes consumed by array:",nishtha.nbytes)
transpose_arr=nishtha.reshape(25,1)
print("transpose of arr using reshape\n",transpose_arr)

original array :
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
dimensions: 1
shape: (25,)
size: 25
data type : float64
bytes consumed by array: 200
transpose of arr using reshape
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


In [4]:
import numpy as np
ucs420_nishtha= np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print( np.mean(ucs420_nishtha))
print(np.median(ucs420_nishtha))
print(np.max(ucs420_nishtha))
print(np.min(ucs420_nishtha))
print(np.unique(ucs420_nishtha))
reshape_ucs420_nishtha=ucs420_nishtha.reshape(4,3)
print("reshape:\n",reshape_ucs420_nishtha)
resize_ucs420_nishtha=np.resize(ucs420_nishtha,(2,6))
print("resize_array:\n",resize_ucs420_nishtha)

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
reshape:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
resize_array:
 [[10 20 30 40 50 60]
 [70 80 90 15 20 35]]
